# Generated by Django 5.1.3 on 2024-12-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_flower_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True),
        ),
    ]
