# Generated by Django 5.1.3 on 2024-12-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flowerCart',
        ),
        migrations.AddField(
            model_name='flowercart',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='flowerCart_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='orders.flowercart'),
            preserve_default=False,
        ),
    ]
