# Generated by Django 5.1.3 on 2024-12-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_flower_stock'),
        ('orders', '0002_remove_order_flowercart_flowercart_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowercart',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flowerCart_id',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.flower')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
